language: node_js
sudo: false
node_js:
  - 0.12
  - 4
  - 6
  - 7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
script:
  - npm test
  - npm run upload
os:
  - osx
  - linux
